In [2]:
import numpy as np

In [78]:
z= np.array([[0,0,0,0,0,0],
              [0,0,0,1,0,0],
              [0,1,0,1,0,0],
              [0,0,1,1,0,0],
              [0,0,0,0,0,0],
              [0,0,0,0,0,0]])

In [79]:
z.shape

(6, 6)

### Ones and Zeros

In [80]:
n = np.zeros(z.shape, dtype=int)
n

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [81]:
n = np.ones(z.shape, dtype=int)
n

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### Operation on array

In [6]:
t = 1 + (2*z + 3)
t

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 6, 4, 4],
       [4, 6, 4, 6, 4, 4],
       [4, 4, 6, 6, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [8]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# Find the indices of array elements that are non-zero, grouped by element.
# np.argwhere(a) is almost the same as np.transpose(np.nonzero(a))
np.argwhere(x>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [10]:
np.transpose(x)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [18]:
r = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])  # dimension: 1, 2, 3 
r
np.swapaxes(r, 0, 2) # dimension 3,2,1

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3]]])

In [45]:
# indices of elements that are non-zero
np.nonzero([1,2,0,0,4,1,0])


(array([0, 1, 4, 5]),)

In [47]:
# or use np.where 
np.where(np.array([1,2,0,0,4,1,0]) > 0)

(array([0, 1, 4, 5]),)

In [21]:
# tile array
a = np.array([0,1,2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [24]:
np.ones((1,2))

array([[1., 1.]])

### numpy vs python list

- hetrogeneous data vs single type data due to which operations becomes much eaiser
- numpy arrays are treated as objects thus less memory usage
- special operations for multidimensional 

### nd array

- size cannot be changed - it creates new array old array is deleted
- homogenous data

### data types
* i - int
* S - string
* u - unsigned integer
* m - datetime
* o - object
* U - unicode string

In [3]:
# find datatype of element in numpy
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array(['I', 'love', 'Interviewbit'])    # Stored as Unicode characters with length of characters ranging from 1 to 12
arr3 = np.array([1, 2, 3, 4], dtype='S')        # Creating numpy array of defined type string

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
<U12
|S1


In [4]:
# reverse array
arr = np.array([1,2,3,4])
arr[::-1]

array([4, 3, 2, 1])

### flipud vs fliplr

- up-down
- left-right

In [5]:
np.flipud(arr)

array([4, 3, 2, 1])

In [64]:
# must be 2-D array
a = np.array([1,2])
'''
12
12
becomes
21
21

'''
np.fliplr(np.vstack((a, a)))

array([[2, 1],
       [2, 1]])

In [68]:
'''
12
34
becomes
34
12
'''

np.flipud(np.vstack((np.array([1,2]), np.array([3,4]))))

array([[3, 4],
       [1, 2]])

In [6]:
np.mean(arr) # 2+3/2

2.5

In [7]:
np.average(arr)

2.5

In [9]:
# counter the number of time an element has appeared in an array
from collections import Counter

c = Counter([1,0,0,0,0,2,3,2,2,3,4,5,4,4,6])
c

Counter({1: 1, 0: 4, 2: 3, 3: 2, 4: 3, 5: 1, 6: 1})

In [11]:
# numpy way
n = np.array([1,0,0,0,0,2,3,2,2,3,4,5,4,4,6])
np.bincount(n)
# [4, 1, 3, 2, 3, 1, 1] - 0 : 4times, 1: 1time, 2: 3times

array([4, 1, 3, 2, 3, 1, 1])

In [31]:
# How is arr[:,0] different from arr[:,[0]]
# arr[:,0] - Returns 0th index elements of all rows. In other words, return the first column elements.

arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr =arr[:,0]
print(new_arr)
# Output:

#  [1 5]
# arr[:,[0]] - This returns the elements of the first column by adding extra dimension to it.

import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr =arr[:,[0]]
print(new_arr)
# Output:

# [[1]
# [5]]


[1 5]
[[1]
 [5]]


#### Multiplication

 - a.dot(B)


In [16]:
# multiple two array
p = np.transpose(arr)
arr.dot(p)

array([[ 30,  70],
       [ 70, 174]])

### Concatenate | hstack vs vstack

In [39]:
'''
axis - 0
a
a
----
axis - 1
aa
'''
np.concatenate((arr, arr), axis=0, out=None)
# same as vstack
np.vstack((arr, arr))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
np.concatenate((arr, arr), axis=1, out=None)
# same as hstack
np.hstack((arr, arr))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [24]:
# panas to numpy to_numpy
import pandas as pd

df = pd.DataFrame(data={"A": [1,2,3]}, index=['i', 'j', 'k'])
df.to_numpy()

array([[1],
       [2],
       [3]])

## Vectorization

- converting python function to numpy function that are optimised for numpy array
- function should take elements as input

In [26]:
def add(n1, n2):
    return n1+n2

In [28]:
vectorize_add = np.vectorize(add)


In [29]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

vectorize_add(a1, a2)


array([5, 7, 9])

In [53]:
## np.where

arr = np.array([1,2,5,234,6,345,8,9,34,45,6,8,0,45,34,5,56,87])
np.where(arr[:] > 50)  # gives us the positions

(array([ 3,  5, 16, 17]),)

In [54]:
## split
np.split(arr, 2)  # gives error if not split is equal partitions

[array([  1,   2,   5, 234,   6, 345,   8,   9,  34]),
 array([45,  6,  8,  0, 45, 34,  5, 56, 87])]

In [56]:
# np.diff
# difference between each element
np.diff(arr)

array([   1,    3,  229, -228,  339, -337,    1,   25,   11,  -39,    2,
         -8,   45,  -11,  -29,   51,   31])

### Moving average  #### not required

In [58]:
import numpy as np
def calculate_moving_average(arr, w):
    return np.convolve(arr, np.ones(w),'valid')/w
# The above-defined function can be then used for finding the moving average as shown in the examples below:

arr1 = np.array([4,5,8,9,3,2,4,2,0,2])
print("Moving average of window length 2: ")
av1 = calculate_moving_average(arr1, 2)
print(av1)

print("Moving average of window length 4: ")
av2 = calculate_moving_average(arr1, 4)
print(av2)

Moving average of window length 2: 
[4.5 6.5 8.5 6.  2.5 3.  3.  1.  1. ]
Moving average of window length 4: 
[6.5  6.25 5.5  4.5  2.75 2.   2.  ]


### strings

In [69]:
carr = np.array(['i', 'love'])

In [72]:
print(np.char.capitalize(carr))
print(np.char.upper(carr))
print(np.char.lower(carr))

['I' 'Love']
['I' 'LOVE']
['i' 'love']


In [73]:
np.char.zfill(carr, 8)

array(['0000000i', '0000love'], dtype='<U8')

In [82]:
np.char.multiply(carr, 3)

array(['iii', 'lovelovelove'], dtype='<U12')