In [1]:
import numpy as np

In [78]:
z= np.array([[0,0,0,0,0,0],
              [0,0,0,1,0,0],
              [0,1,0,1,0,0],
              [0,0,1,1,0,0],
              [0,0,0,0,0,0],
              [0,0,0,0,0,0]])

In [79]:
z.shape

(6, 6)

### Ones and Zeros

In [80]:
n = np.zeros(z.shape, dtype=int)
n

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [81]:
n = np.ones(z.shape, dtype=int)
n

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### random values numpy array

In [187]:
np.empty((2,3))

array([[0.0e+000, 4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323, 2.5e-323]])

### Operation on array

In [6]:
t = 1 + (2*z + 3)
t

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 6, 4, 4],
       [4, 6, 4, 6, 4, 4],
       [4, 4, 6, 6, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [8]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# Find the indices of array elements that are non-zero, grouped by element.
# np.argwhere(a) is almost the same as np.transpose(np.nonzero(a))
np.argwhere(x>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [10]:
np.transpose(x)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [18]:
r = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])  # dimension: 1, 2, 3 
r
np.swapaxes(r, 0, 2) # dimension 3,2,1

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3]]])

In [61]:
# indices of elements that are non-zero
non_z_np = np.array([1,2,0,0,4,1,0])
np.nonzero(non_z_np)
# print(non_z_np[np.nonzero(non_z_np)])

# mask =  non_z_np != 0
# non_z_np[mask]

(array([0, 1, 4, 5]),)

### where

In [47]:
# or use np.where 
np.where(np.array([1,2,0,0,4,1,0]) > 0)

(array([0, 1, 4, 5]),)

In [41]:
# it wil create two single dimension array
p = np.array([[1,2,3], [3,4,5]])
mask = p > 2
print(mask)
p[mask]  # but values will be linear

[[False False  True]
 [ True  True  True]]


array([3, 3, 4, 5])

In [43]:
where_mask = np.where(p > 2)
print(where_mask)
p[where_mask]

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))


array([3, 3, 4, 5])

In [21]:
# tile array
a = np.array([0,1,2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [24]:
np.ones((1,2))

array([[1., 1.]])

### numpy vs python list

- hetrogeneous data vs single type data due to which operations becomes much eaiser
- numpy arrays are treated as objects thus less memory usage
- special operations for multidimensional 
- numpy converts code to machine code instead on byte code

### nd array

- size cannot be changed - it creates new array old array is deleted
- homogenous data

### data types
* i - int
* S - string
* u - unsigned integer
* m - datetime
* o - object
* U - unicode string

In [3]:
# find datatype of element in numpy
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array(['I', 'love', 'Interviewbit'])    # Stored as Unicode characters with length of characters ranging from 1 to 12
arr3 = np.array([1, 2, 3, 4], dtype='S')        # Creating numpy array of defined type string

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
<U12
|S1


In [4]:
# reverse array
arr = np.array([1,2,3,4])
arr[::-1]

array([4, 3, 2, 1])

### flipud vs fliplr

- up-down
- left-right

In [5]:
np.flipud(arr)

array([4, 3, 2, 1])

In [64]:
# must be 2-D array
a = np.array([1,2])
'''
12
12
becomes
21
21

'''
np.fliplr(np.vstack((a, a)))

array([[2, 1],
       [2, 1]])

In [68]:
'''
12
34
becomes
34
12
'''

np.flipud(np.vstack((np.array([1,2]), np.array([3,4]))))

array([[3, 4],
       [1, 2]])

In [185]:
# dstack [one value from each array and create row]
a = np.array([1,5,3,7,8])
b = np.array([5,7,1,9,0])
np.dstack((a,b))

array([[[1, 5],
        [5, 7],
        [3, 1],
        [7, 9],
        [8, 0]]])

In [6]:
np.mean(arr) # 2+3/2

2.5

In [7]:
np.average(arr)

2.5

In [9]:
# counter the number of time an element has appeared in an array
from collections import Counter

c = Counter([1,0,0,0,0,2,3,2,2,3,4,5,4,4,6])
c

Counter({1: 1, 0: 4, 2: 3, 3: 2, 4: 3, 5: 1, 6: 1})

In [133]:
# numpy way
n = np.array([1,0,0,0,0,2,3,2,2,3,4,5,4,4,6])
np.bincount(n)
# [4, 1, 3, 2, 3, 1, 1] - 0 : 4times, 1: 1time, 2: 3times
# index is value and array value is count

array([4, 1, 3, 2, 3, 1, 1])

In [134]:
np.unique(n, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6]), array([4, 1, 3, 2, 3, 1, 1]))

In [31]:
# How is arr[:,0] different from arr[:,[0]]
# arr[:,0] - Returns 0th index elements of all rows. In other words, return the first column elements.

arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr =arr[:,0]
print(new_arr)
# Output:

#  [1 5]
# arr[:,[0]] - This returns the elements of the first column by adding extra dimension to it.

import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr =arr[:,[0]]
print(new_arr)
# Output:

# [[1]
# [5]]


[1 5]
[[1]
 [5]]


#### Multiplication

 - a.dot(B)


In [16]:
# multiple two array
p = np.transpose(arr)
arr.dot(p)

array([[ 30,  70],
       [ 70, 174]])

### Concatenate | hstack vs vstack | insert

In [125]:
'''
axis - 0
a
a
----
axis - 1
aa
'''
np.concatenate((arr, arr), axis=0, out=None)
# same as vstack
np.vstack((arr, arr))

array([[2, 8, 9, 4],
       [9, 4, 9, 4],
       [4, 5, 9, 7],
       [2, 9, 4, 3],
       [2, 8, 9, 4],
       [9, 4, 9, 4],
       [4, 5, 9, 7],
       [2, 9, 4, 3]])

In [126]:
np.concatenate((arr, arr), axis=1, out=None)
# same as hstack
np.hstack((arr, arr))

array([[2, 8, 9, 4, 2, 8, 9, 4],
       [9, 4, 9, 4, 9, 4, 9, 4],
       [4, 5, 9, 7, 4, 5, 9, 7],
       [2, 9, 4, 3, 2, 9, 4, 3]])

In [127]:
np.insert(arr,0, arr, axis=0)

array([[2, 8, 9, 4],
       [9, 4, 9, 4],
       [4, 5, 9, 7],
       [2, 9, 4, 3],
       [2, 8, 9, 4],
       [9, 4, 9, 4],
       [4, 5, 9, 7],
       [2, 9, 4, 3]])

In [24]:
# panas to numpy to_numpy
import pandas as pd

df = pd.DataFrame(data={"A": [1,2,3]}, index=['i', 'j', 'k'])
df.to_numpy()

array([[1],
       [2],
       [3]])

## Vectorization

- converting python function to numpy function that are optimised for numpy array
- function should take elements as input

In [26]:
def add(n1, n2):
    return n1+n2

In [28]:
vectorize_add = np.vectorize(add)


In [29]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

vectorize_add(a1, a2)


array([5, 7, 9])

In [53]:
## np.where

arr = np.array([1,2,5,234,6,345,8,9,34,45,6,8,0,45,34,5,56,87])
np.where(arr[:] > 50)  # gives us the positions

(array([ 3,  5, 16, 17]),)

In [54]:
## split
np.split(arr, 2)  # gives error if not split is equal partitions

[array([  1,   2,   5, 234,   6, 345,   8,   9,  34]),
 array([45,  6,  8,  0, 45, 34,  5, 56, 87])]

### difference if each element with each other

In [62]:
# np.diff
# difference between each element
diffArr = np.array([1,4,2,6,3])
np.diff(diffArr)

array([ 3, -2,  4, -3])

### Moving average  #### not required

In [58]:
import numpy as np
def calculate_moving_average(arr, w):
    return np.convolve(arr, np.ones(w),'valid')/w
# The above-defined function can be then used for finding the moving average as shown in the examples below:

arr1 = np.array([4,5,8,9,3,2,4,2,0,2])
print("Moving average of window length 2: ")
av1 = calculate_moving_average(arr1, 2)
print(av1)

print("Moving average of window length 4: ")
av2 = calculate_moving_average(arr1, 4)
print(av2)

Moving average of window length 2: 
[4.5 6.5 8.5 6.  2.5 3.  3.  1.  1. ]
Moving average of window length 4: 
[6.5  6.25 5.5  4.5  2.75 2.   2.  ]


### strings

In [250]:
carr = np.array(['i', 'love'])

In [251]:
print(np.char.capitalize(carr))
print(np.char.upper(carr))
print(np.char.lower(carr))

['I' 'Love']
['I' 'LOVE']
['i' 'love']


In [252]:
np.char.zfill(carr, 8)

array(['0000000i', '0000love'], dtype='<U8')

In [253]:
np.char.multiply(carr, 3)

array(['iii', 'lovelovelove'], dtype='<U12')

In [258]:
np.char.split(np.array(["akash is studing numpy"], dtype='str'))

array([list(['akash', 'is', 'studing', 'numpy'])], dtype=object)

In [262]:
np.char.join(" ", np.array(["akash", "is", "studying numpy"]))

array(['a k a s h', 'i s', 's t u d y i n g   n u m p y'], dtype='<U27')

In [265]:
np_str = np.array(["akash", "is", "studying numpy"])

len_vec = np.vectorize(len)
len_vec(np_str)

array([ 5,  2, 14])

In [270]:
# find position of first occurence of a string 
arr_str = np.array(["akash", "is", "studyisng numpyis"])
np.char.find(arr_str, sub="is")

array([-1,  0,  5])

### count substring

In [269]:
arr_str = np.array(["akash", "is", "studyisng numpyis"])
np.char.count(arr_str, sub="is")

array([0, 1, 2])

### Empty and full numpy array

In [63]:
import numpy as np
  
# Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)
  
# Create a full array
flla = np.full([3, 3], 55, dtype=int)
print("\n Full Array")
print(flla)

Empty Array
[[0 0 0 1]
 [0 2 1 0]
 [1 1 1 2]]

 Full Array
[[55 55 55]
 [55 55 55]
 [55 55 55]]


## array with zeros / ones

In [64]:
zer = np.zeros([5,5])
print(zer)
ones = np.ones([5,5], dtype=float)
ones

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### check if a list appears in numpy

In [65]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [66]:
True if [1,2,3,4,5] in arr.tolist() else False

True

In [67]:
 arr.tolist()

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]

### Remove rows in Numpy array that contains non-numeric values

In [68]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])   # remove nan

In [69]:
p = ~np.isnan(n_arr).any(axis=1)

In [70]:
# removed the entire row containing np.nan
n_arr[p]

array([[10.5, 22.5,  3.8]])

### the number of occurrences of a sequence in a NumPy array

In [ ]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
print(arr)
seq = [9, 4]
seq

In [ ]:
repr(arr).count("9, 4")

In [ ]:
arr.tolist()

### most frequent element in a numpy array

In [76]:
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
y = np.bincount(x)
y
# np.unique(x, return_counts=True)

array([0, 3, 2, 3, 2])

In [7]:
print(y.argmax()) # gives 1st top highest value

# for all values below code
max_val = max(y)
print("max_val: ", max_val)

for i in range(0, len(y)):
    if y[i] == max_val:
        print(i)

1
max_val:  3
1
3


In [8]:
a1 = np.arange(5)
a2 = np.arange(6)

np.hstack((a1, a2))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

### build an array of all combinations of two NumPy arrays

In [9]:
np.array(np.meshgrid(a1, a2)).reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 0],
       [1, 2],
       [3, 4],
       [0, 1],
       [2, 3],
       [4, 0],
       [1, 2],
       [3, 4],
       [0, 1],
       [2, 3],
       [4, 0],
       [1, 2],
       [3, 4],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 3],
       [3, 3],
       [3, 3],
       [4, 4],
       [4, 4],
       [4, 5],
       [5, 5],
       [5, 5]])

### add a border around numpy array

In [78]:
padArr = np.array([[1,2,3], [4,5,6]])
# np.pad(np.vstack((a1, a1)), pad_width=1)
np.pad(padArr, pad_width=1)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 0, 0, 0, 0]])

## compare two numpy arrays

In [81]:
c1 = np.arange(6)
c2 = np.array([3,4,5,7,8,9])

# works on equal size numpy array
comparison = c1 == c2
comparison

array([False, False, False, False, False, False])

In [82]:
comparison.all()

False

In [13]:
c3 = np.arange(12)
c4 = np.arange(12, 24)

In [14]:
c3 > c4

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [15]:
np.less(c3, c4)
np.less_equal(c3, c4)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

### check if specified values are present

In [16]:
# check 48
if 48 > len(np.bincount(c4)):
    print("element dne")


element dne


In [17]:
cnt = np.array([1.345, 2.345, 3.3456])
1.345 in cnt

True

### diagonals

In [18]:
d3 = np.arange(50).reshape(2,5,5)
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [19]:
np.diagonal(d3, axis1=1, axis2=2)

array([[ 0,  6, 12, 18, 24],
       [25, 31, 37, 43, 49]])

In [20]:
d3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### Swap axes

In [21]:
d3.swapaxes(0,1)

array([[[ 0,  1,  2,  3,  4],
        [25, 26, 27, 28, 29]],

       [[ 5,  6,  7,  8,  9],
        [30, 31, 32, 33, 34]],

       [[10, 11, 12, 13, 14],
        [35, 36, 37, 38, 39]],

       [[15, 16, 17, 18, 19],
        [40, 41, 42, 43, 44]],

       [[20, 21, 22, 23, 24],
        [45, 46, 47, 48, 49]]])

In [22]:
np.nonzero(d3)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        4, 4, 4, 4, 4]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
        3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4,
        0, 1, 2, 3, 4]))

In [23]:
np.flipud(np.arange(6))

array([5, 4, 3, 2, 1, 0])

### numpy readonly

In [24]:
readonly = np.arange(6)
readonly.setflags(write=False)

### max value of a given matrix

In [25]:
matrix = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
matrix.max()

9

In [26]:
print(matrix.sum())
print(matrix[0].sum())

92
23


In [27]:
print(matrix.diagonal().sum())
np.diagonal(matrix).sum()

18


18

In [28]:
matrix2 = np.array([[1, 9, 9, 4], 
                   [9, 4, 19, 0],
                   [4, 0, 45, 7],
                   [1, 9, 4, 3]])
matrix - matrix2

array([[  1,  -1,   0,   0],
       [  0,   0, -10,   4],
       [  0,   5, -36,   0],
       [  1,   0,   0,   0]])

In [29]:
np.subtract(matrix, matrix2)
np.add(matrix, matrix2)

array([[ 3, 17, 18,  8],
       [18,  8, 28,  4],
       [ 8,  5, 54, 14],
       [ 3, 18,  8,  6]])

In [30]:
np.unique(matrix2, return_counts=True)

(array([ 0,  1,  3,  4,  7,  9, 19, 45]), array([2, 2, 1, 4, 1, 4, 1, 1]))

In [31]:
matrix.tolist()

[[2, 8, 9, 4], [9, 4, 9, 4], [4, 5, 9, 7], [2, 9, 4, 3]]

In [32]:
filter_np = np.arange(10)
p = np.where(filter_np % 2 == 0)
filter_np[p]

array([0, 2, 4, 6, 8])

In [33]:
filter_np[filter_np % 2 == 0]

array([0, 2, 4, 6, 8])

## fill nan with average values 

In [46]:
fill_np = np.array([[1,4,2,np.nan,6,4,6,np.nan], [1,4,2,np.nan,6,4,6,np.nan]])
p = np.isnan(fill_np)
fill_np[p] = np.nanmean(fill_np)
fill_np

array([[1.        , 4.        , 2.        , 3.83333333, 6.        ,
        4.        , 6.        , 3.83333333],
       [1.        , 4.        , 2.        , 3.83333333, 6.        ,
        4.        , 6.        , 3.83333333]])

In [234]:
np_negative = np.array([-4, -5, 1, 4, -3])
np_negative

array([-4, -5,  1,  4, -3])

In [235]:
np_negative[np.where(np_negative < 0)] = 0

In [236]:
np_negative

array([0, 0, 1, 4, 0])

### remove columns with non numeric values

In [237]:
fill_np = np.array([[1,4,2,np.nan,6,4,6,np.nan], [1,4,2,np.nan,6,4,6,np.nan]])
fill_np

array([[ 1.,  4.,  2., nan,  6.,  4.,  6., nan],
       [ 1.,  4.,  2., nan,  6.,  4.,  6., nan]])

In [238]:
fill_np[:, ~np.isnan(fill_np).any(axis=0)]

array([[1., 4., 2., 6., 4., 6.],
       [1., 4., 2., 6., 4., 6.]])

In [239]:
np.where(fill_np > 2)

(array([0, 0, 0, 0, 1, 1, 1, 1]), array([1, 4, 5, 6, 1, 4, 5, 6]))

In [240]:
1 in np.arange(6)

True

In [241]:
np.isin(np.arange(6), [2,4,5])

array([False, False,  True, False,  True,  True])

In [242]:
# argsort gives you the sorted arguments
np.argsort(np.empty((1,8)))

array([[0, 1, 5, 7, 4, 2, 6, 3]])

In [243]:
random_np = np.array([1,5,3,25,6,3,2])
random_np = np.sort(random_np)
random_np[:2]

array([1, 2])

In [244]:
random_np[-3:]

array([ 5,  6, 25])

In [245]:
matrix_np = np.array([[1,5,3,25,6,3,2], [1,5,3,25,6,3,2]])
mat = np.matrix(matrix_np)
mat.sort()

In [246]:
mat

matrix([[ 1,  2,  3,  3,  5,  6, 25],
        [ 1,  2,  3,  3,  5,  6, 25]])

In [247]:
random_np = np.array([1,5,3,25,6,3,2])
random_np.sort()

In [248]:
random_np

array([ 1,  2,  3,  3,  5,  6, 25])

### Filter out intergers from float

In [249]:
ini_array = np.array([1,5,3.34,25,6,3.23,2])
result = ini_array[ini_array != ini_array.astype(int)]
result

array([3.34, 3.23])